language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-init' ]; then cd .. && eval "mv $currentfolder generator-init" && cd generator-init; fi

